FROM alpine:3.21

RUN apk update && apk upgrade && apk add --no-cache mariadb mariadb-client

# Create run directory
RUN mkdir -p /run/mysqld /var/lib/mysql && chown -R mysql:mysql /run/mysqld /var/lib/mysql

# Copy entrypoint
COPY conf/mariadb-init.sh /usr/local/bin/mariadb-init.sh
RUN chmod +x /usr/local/bin/mariadb-init.sh

EXPOSE 3306
CMD ["/usr/local/bin/mariadb-init.sh"]
